# Generated by Django 4.1.8 on 2023-04-21 18:08

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('registration01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration01',
            name='thank_you_section',
            field=wagtail.fields.StreamField([('title', wagtail.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'bold', 'italic', 'link'], icon='title', required=False)), ('text', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'ol', 'ul'], required=False)), ('ics', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link'], icon='link', required=False))], blank=True, use_json_field=None),
        ),
    ]
